export const TEXT = {
  en: {
    tabs: { content: 'Content', details: 'Details', tags: 'Tags', media: 'Media' },
    labels: {
      name: 'Name',
      description: 'Description',
      location: 'Location',
      pros: 'Pros',
      cons: 'Cons',
      housingType: 'Housing Type',
      annualPrice: 'Annual Price (USD)',
      applicationFee: 'Application Fee (USD)',
      airConditioning: 'Air Conditioning',
      dining: 'Dining',
      bathroomType: 'Bathroom Type',
      roomOptions: 'Derived Room Options',
      imageUrl: 'Primary Image URL',
      galleryImages: 'Gallery Images',
      floorPlans: 'Floor Plans & Pricing',
      layoutKind: 'Layout Kind',
      bedCount: 'Bed Count',
      bathroomCount: 'Bathroom Count',
      pricePerYear: 'Price / year',
      sqft: 'Sq Ft',
      shortDescription: 'Description',
      planImageUrl: 'Image URL',
      available: 'Available',
      llc: 'Living-Learning Communities (LLC)',
    },
    actions: {
      addPro: 'Add pro',
      addCon: 'Add con',
      addFloorPlan: 'Add floor plan',
      addGalleryImage: 'Add gallery image URL',
      reset: 'Reset to defaults',
      resetting: 'Resetting...',
      save: 'Save',
      saving: 'Saving...',
      saved: 'Saved',
      cancel: 'Cancel',
      upload: 'Upload',
    },
    values: {
      inside: 'Inside',
      nearby: 'Nearby',
      none: 'None',
      communal: 'Communal',
      semiPrivate: 'Semi-Private',
      private: 'Private',
      standard: 'Standard',
      studio: 'Studio',
      suite: 'Suite',
      cluster: 'Cluster',
      noFloorPlans: 'Add at least one floor plan to derive room options.',
    },
    hints: {
      customLocation: 'Or enter a custom location...',
      feePlaceholder: 'Leave empty if none',
      nearbyDining: 'e.g. 5 min walk to Ikenberry Dining Center',
      roomOptions: 'Auto-derived from floor plans',
      llc: 'Click to select LLCs available in this dorm',
    },
    alerts: {
      resetConfirm: 'Reset all overrides for this dorm? Manual edits will be deleted.',
      saveFailed: 'Save failed. Please try again.',
      onlyImages: 'Only image files are supported.',
      imageTooLarge: 'Image size must be 10MB or smaller.',
      imageUploadFailed: 'Image upload failed. Please try again.',
    },
  },
  zh: {
    tabs: { content: '鍐呭', details: '璇︽儏', tags: '鏍囩', media: '濯掍綋' },
    labels: {
      name: '鍚嶇О',
      description: '鎻忚堪',
      location: '浣嶇疆',
      pros: '浼樼偣',
      cons: '缂虹偣',
      housingType: '浣忓绫诲瀷',
      annualPrice: '骞磋垂鐢紙缇庡厓锛�',
      applicationFee: '鐢宠璐癸紙缇庡厓锛�',
      airConditioning: '绌鸿皟',
      dining: '椋熷爞',
      bathroomType: '鍗蕩绫诲瀷',
      roomOptions: '娲剧敓鎴垮瀷',
      imageUrl: '涓诲浘 URL',
      galleryImages: '鍥惧簱鍥剧墖',
      floorPlans: '鎴峰瀷鍥句笌浠锋牸',
      layoutKind: '甯冨眬绫诲瀷',
      bedCount: '搴婁綅鏁�',
      bathroomCount: '鍗蕩鏁�',
      pricePerYear: '骞翠环鏍�',
      sqft: '闈㈢Н',
      shortDescription: '鎻忚堪',
      planImageUrl: '鍥剧墖閾炬帴',
      available: '鍙璁�',
      llc: '瀛︿範鐢熸椿绀惧尯锛圠LC锛�',
    },
    actions: {
      addPro: '娣诲姞浼樼偣',
      addCon: '娣诲姞缂虹偣',
      addFloorPlan: '娣诲姞鎴峰瀷',
      addGalleryImage: '娣诲姞鍥惧簱鍥剧墖閾炬帴',
      reset: '鎭㈠榛樿鏁版嵁',
      resetting: '鎭㈠涓�..',
      save: '淇濆瓨',
      saving: '淇濆瓨涓�..',
      saved: '宸蹭繚瀛�',
      cancel: '鍙栨秷',
      upload: '涓婁紶',
    },
    values: {
      inside: '妤煎唴',
      nearby: '闄勮繎',
      none: '鏃�',
      communal: '鍏叡鍗蕩',
      semiPrivate: '鍗婄嫭绔嬪崼娴�',
      private: '鐙珛鍗蕩',
      standard: '鏍囧噯',
      studio: 'Studio',
      suite: 'Suite',
      cluster: 'Cluster',
      noFloorPlans: '鑷冲皯娣诲姞涓€涓埛鍨嬪浘鍚庢墠浼氱敓鎴愭埧鍨嬨€�',
    },
    hints: {
      customLocation: '鎴栬緭鍏ヨ嚜瀹氫箟浣嶇疆...',
      feePlaceholder: '濡傛棤鍙暀绌�',
      nearbyDining: '渚嬪锛氭琛� 5 鍒嗛挓鍒� Ikenberry Dining Center',
      roomOptions: '浼氭牴鎹埛鍨嬪浘鑷姩鐢熸垚',
      llc: '鐐瑰嚮閫夋嫨璇ュ鑸嶅彲鐢ㄧ殑 LLC',
    },
    alerts: {
      resetConfirm: '纭畾瑕佹仮澶嶉粯璁ゆ暟鎹悧锛熸墍鏈夋墜鍔ㄤ慨鏀归兘浼氳鍒犻櫎銆�',
      saveFailed: '淇濆瓨澶辫触锛岃閲嶈瘯銆�',
      onlyImages: '浠呮敮鎸佷笂浼犲浘鐗囨枃浠躲€�',
      imageTooLarge: '鍥剧墖澶у皬涓嶈兘瓒呰繃 10MB銆�',
      imageUploadFailed: '鍥剧墖涓婁紶澶辫触锛岃閲嶈瘯銆�',
    },
  },
} as const;

export const LOCATION_PRESETS = [
  { value: 'Ikenberry', en: 'Ikenberry', zh: 'Ikenberry' },
  { value: 'Main Quad', en: 'Main Quad', zh: 'Main Quad' },
  { value: 'PAR/FAR', en: 'PAR/FAR', zh: 'PAR/FAR' },
  { value: 'Campustown', en: 'Campustown', zh: 'Campustown' },
  { value: 'South Campus', en: 'South Campus', zh: 'South Campus' },
];

export const LLC_OPTIONS = [
  'Beckwith Residential Community',
  'Business LLC',
  'Exploration LLC',
  'Global Crossroads LLC',
  'Health Professions LLC',
  'Honors LLC',
  'Innovation LLC',
  'Intersections LLC',
  'LEADS LLC',
  'Scholars Community',
  'Sustainability LLC',
  'Transfer Community',
  'Unit One LLC',
  'WIMSE LLC',
];
