export const TEXT = {
  en: {
    tabs: {
      content: 'Content',
      details: 'Details',
      tags: 'Tags',
      media: 'Media',
      history: 'History',
    },
    labels: {
      name: 'Name',
      description: 'Description',
      location: 'Location',
      pros: 'Pros',
      cons: 'Cons',
      housingType: 'Housing Type',
      annualPrice: 'Annual Price (USD)',
      applicationFee: 'Application Fee (USD)',
      airConditioning: 'Air Conditioning',
      dining: 'Dining',
      bathroomType: 'Bathroom Type',
      roomOptions: 'Derived Room Options',
      imageUrl: 'Primary Image URL',
      galleryImages: 'Gallery Images',
      floorPlans: 'Floor Plans & Pricing',
      layoutKind: 'Layout Kind',
      bedCount: 'Bed Count',
      bathroomCount: 'Bathroom Count',
      pricePerYear: 'Price / year',
      sqft: 'Sq Ft',
      shortDescription: 'Description',
      planImageUrl: 'Image URL',
      available: 'Available',
      llc: 'Living-Learning Communities (LLC)',
      address: 'Address',
      addressZh: 'Address (Chinese)',
      website: 'Website URL',
      bedSize: 'Bed Size',
    },
    actions: {
      addPro: 'Add pro',
      addCon: 'Add con',
      addFloorPlan: 'Add floor plan',
      addGalleryImage: 'Add gallery image URL',
      reset: 'Reset to defaults',
      resetting: 'Resetting...',
      save: 'Save',
      saving: 'Saving...',
      saved: 'Saved',
      cancel: 'Cancel',
      upload: 'Upload',
      restore: 'Restore',
      restoring: 'Restoring...',
      loading: 'Loading...',
    },
    values: {
      inside: 'Inside',
      nearby: 'Nearby',
      none: 'None',
      communal: 'Communal',
      semiPrivate: 'Semi-Private',
      private: 'Private',
      standard: 'Standard',
      studio: 'Studio',
      suite: 'Suite',
      cluster: 'Cluster',
      noFloorPlans: 'Add at least one floor plan to derive room options.',
    },
    hints: {
      customLocation: 'Or enter a custom location...',
      feePlaceholder: 'Leave empty if none',
      nearbyDining: 'e.g. 5 min walk to Ikenberry Dining Center',
      roomOptions: 'Auto-derived from floor plans',
      llc: 'Click to select LLCs available in this dorm',
      historyEmpty: 'No edit history yet.',
    },
    alerts: {
      resetConfirm: 'Reset all overrides for this dorm? Manual edits will be deleted.',
      saveFailed: 'Save failed. Please try again.',
      onlyImages: 'Only image files are supported.',
      imageTooLarge: 'Image size must be 10MB or smaller.',
      imageUploadFailed: 'Image upload failed. Please try again.',
      restoreConfirm: 'Restore to this version? Current data will be overwritten.',
      restoreFailed: 'Restore failed. Please try again.',
    },
  },
  zh: {
    tabs: {
      content: '内容',
      details: '详情',
      tags: '标签',
      media: '媒体',
      history: '历史',
    },
    labels: {
      name: '名称',
      description: '描述',
      location: '位置',
      pros: '优点',
      cons: '缺点',
      housingType: '住宿类型',
      annualPrice: '年费用（美元）',
      applicationFee: '申请费（美元）',
      airConditioning: '空调',
      dining: '食堂',
      bathroomType: '卫浴类型',
      roomOptions: '自动派生房型',
      imageUrl: '主图链接',
      galleryImages: '图库图片',
      floorPlans: '户型图与价格',
      layoutKind: '布局类型',
      bedCount: '床位数',
      bathroomCount: '卫浴数量',
      pricePerYear: '年价格',
      sqft: '平方英尺',
      shortDescription: '描述',
      planImageUrl: '图片链接',
      available: '可预订',
      llc: '学习生活社区（LLC）',
      address: '地址',
      addressZh: '地址（中文）',
      website: '官网链接',
      bedSize: '床型',
    },
    actions: {
      addPro: '添加优点',
      addCon: '添加缺点',
      addFloorPlan: '添加户型',
      addGalleryImage: '添加图库图片链接',
      reset: '恢复默认值',
      resetting: '恢复中...',
      save: '保存',
      saving: '保存中...',
      saved: '已保存',
      cancel: '取消',
      upload: '上传',
      restore: '还原',
      restoring: '还原中...',
      loading: '加载中...',
    },
    values: {
      inside: '楼内',
      nearby: '附近',
      none: '无',
      communal: '公共卫浴',
      semiPrivate: '半独立卫浴',
      private: '独立卫浴',
      standard: '标准',
      studio: 'Studio',
      suite: 'Suite',
      cluster: 'Cluster',
      noFloorPlans: '至少添加一个户型图后，系统才会自动生成房型。',
    },
    hints: {
      customLocation: '或输入自定义位置...',
      feePlaceholder: '如无可留空',
      nearbyDining: '例如：步行 5 分钟到 Ikenberry Dining Center',
      roomOptions: '会根据户型图自动生成',
      llc: '点击选择该宿舍所属的 LLC',
      historyEmpty: '暂无编辑记录。',
    },
    alerts: {
      resetConfirm: '确定要恢复这栋宿舍的默认数据吗？所有手动修改都会被删除。',
      saveFailed: '保存失败，请重试。',
      onlyImages: '仅支持上传图片文件。',
      imageTooLarge: '图片大小不能超过 10MB。',
      imageUploadFailed: '图片上传失败，请重试。',
      restoreConfirm: '确定要还原到这个版本吗？当前数据将被覆盖。',
      restoreFailed: '还原失败，请重试。',
    },
  },
} as const;
