version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "cron"
      cronjob: "30 11 * * 3,6"
    open-pull-requests-limit: 10
    groups:
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-major:
        dependency-type: "production"
        update-types:
          - "major"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "cron"
      cronjob: "30 11 * * 3,6"
    open-pull-requests-limit: 10
    groups:
      production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-major:
        dependency-type: "production"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 11 * * 3,6"
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        update-types:
          - "minor"
          - "patch"
