import { defineConfig } from "vite-plus"

export default defineConfig({
  fmt: {
    singleQuote: false,
    semi: false,
    trailingComma: "es5",
    printWidth: 80,
    sortTailwindcss: {},
    ignorePatterns: [
      "*.md",
      "node_modules",
      "pnpm-lock.yaml",
      "build",
      "dist",
      "*.env.*",
      "*.jsonc",
      "unimcp",
      "data_collection",
    ],
  },
  lint: {
    plugins: [
      "typescript",
      "unicorn",
      "oxc",
      "import",
      "react",
      "jsx-a11y",
      "react-perf",
      "promise",
      "node",
      "vitest",
    ],
    categories: {
      correctness: "error",
      perf: "error",
      suspicious: "warn",
      pedantic: "warn",
    },
    env: {
      builtin: true,
    },
    settings: {
      react: {
        version: "19.2.6",
      },
      "jsx-a11y": {
        components: {
          Image: "img",
          Link: "a",
          Button: "button",
          Input: "input",
          Select: "select",
          Textarea: "textarea",
        },
      },
    },
    options: {
      reportUnusedDisableDirectives: "warn",
      respectEslintDisableDirectives: true,
      typeAware: true,
      typeCheck: true,
    },
    ignorePatterns: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "coverage/**",
      ".wrangler/**",
      "app/.vite/**",
      "app/.debug/**",
      "app/tests/artifacts/**",
      "app/src/legacy/**",
      "src/legacy/**",
      "app/src/components/housing/legacy/**",
      "src/components/housing/legacy/**",
      "supabase/.temp/**",
      "**/*.min.*",
      "**/*.generated.*",
      "**/*.gen.*",
      "**/worker-configuration.d.ts",
    ],
    rules: {
      "no-console": "allow",
      "no-magic-numbers": "allow",

      eqeqeq: "warn",
      curly: "warn",
      "no-throw-literal": "warn",
      "no-else-return": "warn",
      "no-shadow": "warn",
      "no-duplicate-imports": "off",
      "no-nested-ternary": "warn",
      "sort-imports": [
        "warn",
        { ignoreDeclarationSort: true, allowSeparatedGroups: true },
      ],
      "max-params": ["warn", { max: 4 }],
      "no-underscore-dangle": "off",
      "no-template-curly-in-string": "warn",
      "no-var": "warn",
      "prefer-const": "warn",
      "no-void": "off",
      "no-empty-function": "warn",
      "no-await-in-loop": "warn",
      "max-lines-per-function": "off",
      "max-lines": "off",
      "require-unicode-regexp": "off",
      "no-inline-comments": "off",
      "require-await": "off",
      "max-classes-per-file": ["warn", { max: 3 }],
      "max-depth": ["warn", { max: 5 }],
      "no-negated-condition": "off",

      "typescript/ban-ts-comment": [
        "warn",
        {
          "ts-expect-error": "allow-with-description",
          "ts-ignore": "true",
          "ts-nocheck": "true",
        },
      ],
      "typescript/no-non-null-assertion": "warn",
      "typescript/array-type": ["warn", { default: "array-simple" }],
      "typescript/consistent-type-imports": [
        "warn",
        {
          prefer: "type-imports",
          fixStyle: "inline-type-imports",
        },
      ],
      "typescript/no-explicit-any": "warn",

      "react/exhaustive-deps": "warn",
      "react/no-unstable-nested-components": "error",
      "react/self-closing-comp": "warn",
      "react/button-has-type": "warn",
      "react/jsx-curly-brace-presence": [
        "warn",
        { props: "never", children: "never" },
      ],
      "react/jsx-fragments": ["warn", "syntax"],
      "react/no-danger": "warn",
      "react/react-in-jsx-scope": "off",

      "jsx-a11y/no-access-key": "warn",
      "jsx-a11y/no-autofocus": "warn",
      "jsx-a11y/no-aria-hidden-on-focusable": "error",
      "jsx-a11y/anchor-ambiguous-text": "warn",
      "jsx-a11y/tabindex-no-positive": "warn",
      "jsx-a11y/prefer-tag-over-role": "warn",
      "jsx-a11y/control-has-associated-label": "warn",
      "jsx-a11y/no-static-element-interactions": "warn",
      "jsx-a11y/click-events-have-key-events": "warn",

      "react-perf/jsx-no-jsx-as-prop": "warn",
      "react-perf/jsx-no-new-array-as-prop": "warn",
      "react-perf/jsx-no-new-function-as-prop": "warn",
      "react-perf/jsx-no-new-object-as-prop": "warn",

      "unicorn/consistent-assert": "warn",
      "unicorn/explicit-length-check": "warn",
      "unicorn/new-for-builtins": "warn",
      "unicorn/prefer-string-starts-ends-with": "warn",
      "unicorn/throw-new-error": "warn",
      "unicorn/consistent-function-scoping": "warn",
      "unicorn/no-useless-promise-resolve-reject": "warn",
      "unicorn/no-useless-undefined": "warn",
      "unicorn/no-useless-switch-case": "warn",
      "unicorn/no-negation-in-equality-check": "error",

      "promise/prefer-await-to-then": "warn",
      "promise/param-names": "warn",
      "promise/no-callback-in-promise": "warn",

      "import/no-self-import": "error",
      "import/no-empty-named-blocks": "error",
      "import/no-webpack-loader-syntax": "error",
      "import/no-amd": "error",
      "import/no-cycle": ["error", { ignoreTypes: true, maxDepth: 10 }],
      "import/consistent-type-specifier-style": ["warn", "prefer-inline"],
      "import/first": "warn",
      "import/no-named-as-default": "warn",
      "import/newline-after-import": "warn",
      "import/no-default-export": "off",
      "import/no-named-export": "off",
      "import/no-namespace": "off",
      "import/exports-last": "off",
      "import/group-exports": "off",
      "import/prefer-default-export": "off",
      "import/no-unassigned-import": "off",
      "import/no-anonymous-default-export": "off",
      "import/max-dependencies": "off",
    },
    overrides: [
      {
        files: [
          "app/src/**/*.{ts,tsx}",
          "app/functions/**/*.{ts,tsx}",
          "src/**/*.{ts,tsx}",
          "functions/**/*.{ts,tsx}",
        ],
        env: {
          browser: true,
          worker: true,
          serviceworker: true,
        },
        rules: {
          "import/no-nodejs-modules": "warn",
        },
      },
      {
        files: ["**/*.tsx"],
        rules: {
          "react/jsx-max-depth": ["warn", { max: 8 }],
          "react/display-name": "warn",
          "react-perf/jsx-no-new-function-as-prop": "off",
          "react-perf/jsx-no-new-object-as-prop": "off",
          "react-perf/jsx-no-new-array-as-prop": "off",
          "react-perf/jsx-no-jsx-as-prop": "off",
        },
      },
      {
        files: ["api/src/**/*.{js,mjs,cjs,ts}"],
        env: {
          node: true,
          worker: true,
          serviceworker: true,
        },
        rules: {
          "node/no-exports-assign": "error",
          "node/handle-callback-err": "warn",
          "node/no-path-concat": "warn",
          "node/no-new-require": "warn",
        },
      },
      {
        files: ["app/src/**/*.ts"],
        rules: {
          "import/exports-last": "warn",
          "import/no-default-export": "warn",
          "import/no-mutable-exports": "warn",
        },
      },
      {
        files: [
          "**/*.test.{js,jsx,ts,tsx}",
          "**/*.spec.{js,jsx,ts,tsx}",
          "**/__tests__/**/*.{js,jsx,ts,tsx}",
        ],
        env: {
          node: true,
          vitest: true,
        },
        rules: {
          "no-empty-function": "off",
          "typescript/no-non-null-assertion": "off",
          "typescript/no-explicit-any": "off",
          "max-params": "off",
          "react-perf/jsx-no-new-function-as-prop": "off",
          "react-perf/jsx-no-new-object-as-prop": "off",
          "react-perf/jsx-no-new-array-as-prop": "off",
          "react-perf/jsx-no-jsx-as-prop": "off",
          "import/no-nodejs-modules": "off",
          "vitest/prefer-expect-assertions": [
            "warn",
            {
              onlyFunctionsWithAsyncKeyword: true,
              onlyFunctionsWithExpectInCallback: true,
            },
          ],
          "vitest/no-commented-out-tests": "warn",
          "vitest/no-identical-title": "error",
          "vitest/prefer-to-be": "warn",
          "vitest/prefer-to-contain": "warn",
          "vitest/prefer-to-have-length": "warn",
          "vitest/prefer-hooks-in-order": "warn",
          "vitest/prefer-hooks-on-top": "warn",
          "vitest/require-to-throw-message": "warn",
          "vitest/no-interpolation-in-snapshots": "warn",
          "vitest/consistent-test-it": ["warn", { fn: "it" }],
        },
      },
      {
        files: [
          "app/scripts/**/*.{js,mjs,cjs,ts}",
          "scripts/**/*.{js,mjs,cjs,ts}",
          "dorm_scripts/**/*.{js,mjs,cjs,ts}",
        ],
        env: {
          node: true,
        },
        rules: {
          "no-console": "off",
          "node/no-path-concat": "warn",
          "node/no-new-require": "warn",
          "oxc/no-async-endpoint-handlers": "off",
        },
      },
      {
        files: ["**/*.cjs"],
        rules: {
          "unicorn/prefer-top-level-await": "off",
        },
      },
    ],
  },
})
