/**
 * @file ./src/components/housing/constants/dormData.ts
 * @description Housing (Dorms) Component / Module
 * @description_zh 此文件属于 Housing 业务域（限界上下文）。请勿在此引入其他业务（如 chat, library）的代码。保持高内聚，不要把 Housing 独有的逻辑泄露到外层全局目录。
 * @rules See docs/FILE_RULES.md. Follow the Colocation Principle.
 */

import { type Dorm } from "../types/index"
import { normalizeDorm } from "../../../utils/roomOptions"
import { finalizeDormRecord } from "../../../utils/dormData"
import { applyDormOfficialOverride } from "./dormOfficialOverrides"

// Accurate UIUC dorm coordinates based on campus geography
// Campus reference: Main Quad (40.1074, -88.2317), Engineering Quad (40.1130, -88.2280)

const RAW_UIUC_DORMS: Dorm[] = [
  {
    id: "isr",
    name: "Illinois Street Residence (ISR)",
    name_zh: "",
    location: "Main Quad",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Engineering",
      "Renovated",
      "Modern",
      "STEM",
      "Near Main Quad",
      "Near Engineering",
      "Near ARC/CRCE",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: true,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: ["Engineering LLC", "Innovation LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "studyLounge", "laundry", "busStop"],
      lifestyle: ["llc"],
      llcNames: ["Innovation LLC", "Sustainability LLC", "Honors LLC"],
    },
    description:
      "Located conveniently close to engineering quad, ISR features a newly renovated dining center and modern rooms. It is a hub for STEM majors.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=1",
    pros: [
      "Right next to Grainger Engineering Library",
      "Brand new dining facility",
      "Modern amenities",
    ],
    pros_zh: [],
    cons: [
      "Can be competitive to get into",
      "Smaller room sizes in older wings",
    ],
    cons_zh: [],
    price: 14500,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B", "2B2B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 14800,
        sqft: 130,
        description: "Single room with shared bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 14200,
        sqft: 200,
        description: "Double room with shared bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 13500,
        sqft: 280,
        description: "Triple room with shared bathroom",
        available: true,
      },
      {
        type: "2B2B",
        price: 15000,
        sqft: 240,
        description: "Double room with semi-private bathroom",
        available: true,
      },
    ],
    lat: 40.11027312975463,
    lng: -88.22187818321625,
  },
  // Ikenberry North Halls - split from compound entry
  {
    id: "nugent",
    name: "Nugent Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Social",
      "Modern",
      "Popular",
      "Near Main Quad",
      "Near Engineering",
      "Near ARC/CRCE",
      "Near Ikenberry Dining",
      "Elevator",
      "Laundry",
      "Pool",
      "Gym Nearby",
      "LEADS LLC",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: true,
      pool: true,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: ["LEADS LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty", "llc"],
      llcNames: ["Business LLC", "Beckwith Residential Community"],
    },
    description:
      "One of the newest halls on campus offering premium amenities. Located near to ARC gym and Memorial Stadium. Known for being very social.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=2",
    pros: [
      "Very modern rooms",
      "Close to the ARC (Gym)",
      "Great social atmosphere",
    ],
    pros_zh: [],
    cons: ["Most expensive options", "Far from engineering quad"],
    cons_zh: [],
    price: 15200,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "4B2B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 15500,
        sqft: 140,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NUGENT-1B1B.png",
        description: "Single room with semi-private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 15200,
        sqft: 220,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NUGENT-2B1B.png",
        description: "Double room with semi-private bathroom",
        available: true,
      },
      {
        type: "4B2B",
        price: 14800,
        sqft: 450,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NUGENT-4B2B.png",
        description: "Quad suite with 2 bathrooms",
        available: true,
      },
    ],
    lat: 40.1038849685309,
    lng: -88.23723829865558,
  },
  {
    id: "wassaja",
    name: "Wassaja Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Social",
      "Modern",
      "Popular",
      "Near Main Quad",
      "Near Engineering",
      "Near ARC/CRCE",
      "Near Ikenberry Dining",
      "Elevator",
      "Laundry",
      "Pool",
      "Gym Nearby",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: true,
      pool: true,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty"],
    },
    description:
      "Named after the first Native American graduate of UIUC. A modern hall in Ikenberry North with premium amenities near the ARC.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=2a",
    pros: [
      "Very modern rooms",
      "Close to the ARC (Gym)",
      "Great social atmosphere",
    ],
    pros_zh: [],
    cons: ["Most expensive options", "Far from engineering quad"],
    cons_zh: [],
    price: 15200,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "4B2B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 15500,
        sqft: 140,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WASSAJA-1B1B.png",
        description: "Single room with semi-private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 15200,
        sqft: 220,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WASSAJA-2B1B.png",
        description: "Double room with semi-private bathroom",
        available: true,
      },
      {
        type: "4B2B",
        price: 14800,
        sqft: 450,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WASSAJA-4B2B.png",
        description: "Quad suite with 2 bathrooms",
        available: true,
      },
    ],
    lat: 40.103508532497905,
    lng: -88.23783939855508,
  },
  {
    id: "bousefield",
    name: "Bousefield Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Social",
      "Modern",
      "Popular",
      "Near Main Quad",
      "Near Engineering",
      "Near ARC/CRCE",
      "Near Ikenberry Dining",
      "Elevator",
      "Laundry",
      "Pool",
      "Gym Nearby",
      "Focus LLC",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: true,
      pool: true,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: ["Focus LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["llc"],
      llcNames: ["Transfer Community"],
    },
    description:
      "A modern hall in Ikenberry North featuring the Focus Interdisciplinary Sciences Living-Learning Community.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=2b",
    pros: ["Very modern rooms", "Close to the ARC (Gym)", "Focus LLC"],
    pros_zh: [],
    cons: ["Most expensive options", "Far from engineering quad"],
    cons_zh: [],
    price: 15200,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "4B2B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 15500,
        sqft: 140,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BOUSEFIELD-1B1B.png",
        description: "Single room with semi-private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 15200,
        sqft: 220,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BOUSEFIELD-2B1B.png",
        description: "Double room with semi-private bathroom",
        available: true,
      },
      {
        type: "4B2B",
        price: 14800,
        sqft: 450,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BOUSEFIELD-4B2B.png",
        description: "Quad suite with 2 bathrooms",
        available: true,
      },
    ],
    lat: 40.10189634941614,
    lng: -88.2380594197237,
  },
  {
    id: "par",
    name: "Pennsylvania Avenue Residence (PAR)",
    name_zh: "",
    location: "PAR/FAR",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Diverse",
      "Late Night Dining",
      "Bus Routes",
      "Near Business",
      "Elevator",
      "Laundry",
      "Gender-Inclusive",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: false,
      nearEngineering: false,
      nearBusiness: true,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "studyLounge", "laundry", "convenienceStore"],
      lifestyle: ["socialParty", "llc"],
      llcNames: ["Intersections LLC", "Global Crossroads LLC"],
    },
    description:
      'PAR is known for its diversity and famous late-night dining options. It features "Babcock" and "Carr" halls. A bit further south but well connected by bus.',
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=3",
    pros: [
      "Late night dining is a lifesaver",
      "Very diverse community",
      "Good bus access",
    ],
    pros_zh: [],
    cons: ["Far from Green Street", "Shared community bathrooms"],
    cons_zh: [],
    price: 13800,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 14200,
        sqft: 120,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/PAR-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 13800,
        sqft: 180,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/PAR-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 13200,
        sqft: 250,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/PAR-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.1000121975501,
    lng: -88.22015709284125,
  },
  {
    id: "far",
    name: "Florida Avenue Residence (FAR)",
    name_zh: "",
    location: "PAR/FAR",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Quiet",
      "Trellis Dining",
      "South Campus",
      "Near Business",
      "Laundry",
      "Quiet Floors",
      "Gender-Inclusive",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: false,
      nearEngineering: false,
      nearBusiness: true,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["studyLounge", "laundry", "kitchen"],
      lifestyle: ["quiet", "internationalFriendly", "llc"],
      llcNames: ["WIMSE LLC", "Health Professions LLC"],
    },
    description:
      "Located across from PAR, FAR offers air-conditioned rooms and Oglesby/Trelease halls. Known for a slightly quieter atmosphere than Ike.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=4",
    pros: ["Air conditioned", "Weekly soul food night", "Relaxed vibe"],
    pros_zh: [],
    cons: ["Older building style", "Far from main quad"],
    cons_zh: [],
    price: 9200,
    priceRange: "$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 9500,
        sqft: 110,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/FAR-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 9200,
        sqft: 170,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/FAR-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 8800,
        sqft: 240,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/FAR-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.098956890499174,
    lng: -88.22096763817163,
  },
  {
    id: "allen",
    name: "Allen Hall",
    name_zh: "",
    location: "Main Quad",

    housingType: "URH",
    ac: false,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Artsy",
      "Unit One LLC",
      "Music",
      "Near Main Quad",
      "No AC",
      "Laundry",
      "Kitchen",
      "Quiet Floors",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: true,
      kitchen: true,
      parking: false,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: ["Unit One LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["noAc", "olderBuilding"],
      facilities: ["musicRooms", "studyLounge", "laundry", "kitchen"],
      lifestyle: ["artsyCreative", "internationalFriendly", "llc", "quiet"],
      llcNames: ["Unit One LLC"],
    },
    description:
      "Home to the Unit One LLC, Allen is a hub for creative students. It features music practice rooms, a recording studio, and guest-in-residence programs.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=5",
    pros: [
      "Incredible community and programs",
      "In-house dining hall",
      "Creative atmosphere",
    ],
    pros_zh: [],
    cons: ["No Air Conditioning (usually)", "Older facilities"],
    cons_zh: [],
    price: 8500,
    priceRange: "$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 8800,
        sqft: 105,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ALLEN-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 8500,
        sqft: 160,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ALLEN-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 8000,
        sqft: 220,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ALLEN-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.10411647399734,
    lng: -88.22101625773642,
  },
  {
    id: "busey-evans",
    name: "Busey-Evans",
    name_zh: "",
    location: "Main Quad",

    housingType: "URH",
    ac: false,
    dining: "nearby",
    bathroomType: "communal",
    tags: [
      "Historic",
      "Quiet",
      "Female-Identified",
      "Near Main Quad",
      "Laundry",
      "Study Rooms",
      "Quiet Floors",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: false,
      gymNearby: false,
      pool: false,
      genderInclusive: false,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["noAc", "olderBuilding"],
      facilities: ["studyLounge", "laundry"],
      lifestyle: ["quiet"],
    },
    description:
      "A historic residence hall primarily for female-identified students. Known for its beautiful architecture and quiet, study-focused environment.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=6",
    pros: [
      "Very quiet and safe",
      "Beautiful architecture",
      "Close to Krannert Center",
    ],
    pros_zh: [],
    cons: ["No AC in many parts", "Less social party scene"],
    cons_zh: [],
    price: 8800,
    priceRange: "$$",
    roomTypes: ["1B1B", "2B1B", "Studio"],
    floorPlans: [
      {
        type: "1B1B",
        price: 9000,
        sqft: 115,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BUSEYEVANS-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 8800,
        sqft: 170,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BUSEYEVANS-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 9500,
        sqft: 140,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BUSEYEVANS-Studio.png",
        description: "Private room with sink",
        available: true,
      },
    ],
    lat: 40.10577232571417,
    lng: -88.22323498533768,
  },
  // Ikenberry South Halls - split from compound entry
  {
    id: "snyder",
    name: "Snyder Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Social",
      "Traditional",
      "Substance-Free",
      "Near Main Quad",
      "Near Business",
      "Near Ikenberry Dining",
      "Laundry",
      "Study Rooms",
      "Substance-Free",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: true,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: true,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty", "llc"],
      llcNames: ["Exploration LLC"],
    },
    description:
      'A substance-free hall in Ikenberry South. Part of the traditional "Six Pack" with good access to Ike Dining Hall.',
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=7",
    pros: [
      "Close to Ike Dining Hall",
      "Substance-free environment",
      "Social environment",
    ],
    pros_zh: [],
    cons: ["Older buildings", "Community bathrooms"],
    cons_zh: [],
    price: 11200,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 11500,
        sqft: 115,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SNYDER-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11200,
        sqft: 175,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SNYDER-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 10800,
        sqft: 240,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SNYDER-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.1022174939617,
    lng: -88.23541624956036,
  },
  {
    id: "hopkins",
    name: "Hopkins Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "LEADS LLC",
      "Social",
      "Near Main Quad",
      "Near Business",
      "Near Ikenberry Dining",
      "Ike South",
      "Laundry",
      "Study Rooms",
      "LEADS LLC",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: ["LEADS LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: true,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty"],
    },
    description:
      'Part of the "Six Pack" in Ikenberry South. Home to the LEADS Living-Learning Community. Known for a strong sense of community.',
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=8",
    pros: ["Great community events", "Close to Ike Dining", "AC included"],
    pros_zh: [],
    cons: ["Older building", "Communal bathrooms"],
    cons_zh: [],
    price: 11200,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 11500,
        sqft: 115,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HOPKINS-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11200,
        sqft: 175,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HOPKINS-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 10800,
        sqft: 240,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HOPKINS-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.10260589874599,
    lng: -88.23785331375801,
  },
  {
    id: "weston",
    name: "Weston Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Exploration LLC",
      "Freshmen",
      "Social",
      "Near Main Quad",
      "Near Business",
      "Near Ikenberry Dining",
      "Laundry",
      "Exploration LLC",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: ["Exploration LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: true,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty", "llc"],
      llcNames: ["Exploration LLC", "LEADS LLC"],
    },
    description:
      "Located in Ikenberry North, Weston houses the Exploration LLC. It is extremely popular among freshmen and known for being very social.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=9",
    pros: [
      "Prime location in Ike North",
      "Very social atmosphere",
      "Exploration LLC support",
    ],
    pros_zh: [],
    cons: ["Loud on weekends", "Communal bathrooms"],
    cons_zh: [],
    price: 11500,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 11800,
        sqft: 120,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WESTON-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11500,
        sqft: 180,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WESTON-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 11000,
        sqft: 250,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/WESTON-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.10299241417007,
    lng: -88.23530433294022,
  },
  {
    id: "scott",
    name: "Scott Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Social",
      "Transfer Cluster",
      "Ike South",
      "Elevator",
      "Laundry",
      "Study Rooms",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty"],
    },
    description:
      "A large residence hall in Ikenberry South. Features a Transfer Community and is known for being a very social hub with easy access to the quad.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=10",
    pros: [
      "Social vibe",
      "Close to bus stops",
      "Good location for Gies business",
    ],
    pros_zh: [],
    cons: ["Elevators can be slow", "Older facilities"],
    cons_zh: [],
    price: 11200,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 11500,
        sqft: 115,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SCOTT-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11200,
        sqft: 175,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SCOTT-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 10800,
        sqft: 240,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SCOTT-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.10210930610599,
    lng: -88.23675776021224,
  },
  // Taft and Van Doren - split from TVD compound entry
  {
    id: "taft",
    name: "Taft Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Historic",
      "Small Community",
      "Near Main Quad",
      "Near Ikenberry Dining",
      "Ike South",
      "Laundry",
      "Affordable",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty", "llc"],
      llcNames: ["Scholars Community"],
    },
    description:
      "A smaller historic hall in Ikenberry South connected to Van Doren. Known for tight-knit community and unique room layouts.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=14",
    pros: ["Unique room layouts", "Close to Ike dining", "Affordable"],
    pros_zh: [],
    cons: ["No AC", "Long walk to engineering"],
    cons_zh: [],
    price: 6200,
    priceRange: "$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 6500,
        sqft: 100,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/TAPT-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 6200,
        sqft: 150,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/TAPT-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 5900,
        sqft: 200,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/TAPT-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.10197529283074,
    lng: -88.23368088266433,
  },
  {
    id: "van-doren",
    name: "Van Doren Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "semi-private",
    tags: [
      "Historic",
      "Small Community",
      "Near Main Quad",
      "Near Ikenberry Dining",
      "Ike South",
      "Laundry",
      "Affordable",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: false,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry"],
      lifestyle: ["socialParty"],
    },
    description:
      "A smaller historic hall in Ikenberry South connected to Taft. Features diverse room shapes and a close community feel.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=14a",
    pros: ["Unique room layouts", "Close to Ike dining", "Affordable"],
    pros_zh: [],
    cons: ["No AC", "Long walk to engineering"],
    cons_zh: [],
    price: 6200,
    priceRange: "$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 6500,
        sqft: 100,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/VANDOREN-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 6200,
        sqft: 150,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/VANDOREN-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 5900,
        sqft: 200,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/VANDOREN-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.101684942573044,
    lng: -88.23406047469018,
  },
  {
    id: "daniels",
    name: "Daniels Hall",
    name_zh: "",
    location: "Main Quad",

    housingType: "URH",
    ac: false,
    dining: "nearby",
    bathroomType: "communal",
    tags: [
      "Upperclassmen",
      "Quiet",
      "Near Main Quad",
      "Near Green Street",
      "Private Bath",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Quiet Floors",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: true,
      parking: false,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: true,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["noAc", "olderBuilding"],
      facilities: ["studyLounge", "laundry"],
      lifestyle: ["quiet"],
    },
    description:
      "Reserved for sophomores and above. Daniels offers single and double rooms with private or semi-private bathrooms. Very quiet and academically focused.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=11",
    pros: [
      "Private/Semi-private bathrooms",
      "Quiet study environment",
      "Close to Green St",
    ],
    pros_zh: [],
    cons: ["No freshmen allowed", "Less social interaction"],
    cons_zh: [],
    price: 14200,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "2B2B", "Studio"],
    floorPlans: [
      {
        type: "1B1B",
        price: 14500,
        sqft: 135,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/DANIELS-1B1B.png",
        description: "Single room with private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 14200,
        sqft: 210,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/DANIELS-2B1B.png",
        description: "Double room with semi-private bathroom",
        available: true,
      },
      {
        type: "2B2B",
        price: 15500,
        sqft: 250,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/DANIELS-2B2B.png",
        description: "Double room with private bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 15200,
        sqft: 180,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/DANIELS-Studio.png",
        description: "Private studio with kitchenette",
        available: true,
      },
    ],
    lat: 40.110818977382294,
    lng: -88.22180529084652,
  },
  {
    id: "sherman",
    name: "Sherman Hall",
    name_zh: "",
    location: "Campustown",

    housingType: "URH",
    ac: true,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Upperclassmen",
      "Singles",
      "Graduate",
      "Near Main Quad",
      "Near Green Street",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Study Rooms",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: true,
      parking: false,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: true,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["studyLounge", "laundry", "busStop"],
      lifestyle: ["llc"],
      llcNames: ["Intersections LLC"],
    },
    description:
      "Located near the library and psychology building. Sherman is popular for its single rooms and graduate student population. Very independent living style.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=12",
    pros: [
      "Single rooms available",
      "Great central location",
      "Mature atmosphere",
    ],
    pros_zh: [],
    cons: ["Rooms are small", "No meal plan requirement (can be a pro)"],
    cons_zh: [],
    price: 12800,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "Studio"],
    floorPlans: [
      {
        type: "1B1B",
        price: 13000,
        sqft: 110,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SHERMAN-1B1B.png",
        description: "Single room with private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 12500,
        sqft: 190,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SHERMAN-2B1B.png",
        description: "Double room with semi-private bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 14000,
        sqft: 150,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/SHERMAN-Studio.png",
        description: "Private studio with kitchenette",
        available: true,
      },
    ],
    lat: 40.1071305724729,
    lng: -88.23231258832209,
  },
  {
    id: "lar",
    name: "Lincoln Avenue Residence (LAR)",
    name_zh: "",
    location: "South Campus",

    housingType: "URH",
    ac: false,
    dining: "inside",
    bathroomType: "communal",
    tags: [
      "Scholars",
      "Quiet",
      "Near Main Quad",
      "Near ARC/CRCE",
      "Sustainability LLC",
      "Laundry",
      "Study Rooms",
      "Scholars LLC",
    ],
    structuredTags: {
      elevator: false,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: false,
      gymNearby: true, // Close to CRCE
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: ["Scholars LLC", "Sustainability LLC"],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["noAc", "olderBuilding"],
      facilities: ["studyLounge", "laundry", "kitchen"],
      lifestyle: ["quiet", "internationalFriendly", "llc"],
      llcNames: ["Scholars Community"],
    },
    description:
      "Home to the Scholars (Leonard) and Sustainability (Shelden) communities. A quieter hall connected to Allen Hall, sharing dining facilities.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=13",
    pros: [
      "Quiet study environment",
      "Connected to Allen dining",
      "Close to CRCE gym",
    ],
    pros_zh: [],
    cons: ["No AC", "Older building architecture"],
    cons_zh: [],
    price: 9000,
    priceRange: "$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 9200,
        sqft: 108,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/LAR-1B1B.png",
        description: "Single room with community bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 9000,
        sqft: 165,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/LAR-2B1B.png",
        description: "Double room with community bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 8800,
        sqft: 230,
        imageUrl: "https://housing.illinois.edu/Images/FloorPlans/LAR-3B1B.png",
        description: "Triple room with community bathroom",
        available: true,
      },
    ],
    lat: 40.104154937761855,
    lng: -88.21994736520489,
  },
  {
    id: "bromley",
    name: "Bromley Hall",
    name_zh: "",
    location: "Campustown",

    housingType: "PCH",
    ac: true,
    dining: "nearby",
    bathroomType: "private",
    tags: [
      "Social",
      "PCH",
      "Near Engineering",
      "Near Green Street",
      "Pool",
      "Greek Life",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Parking",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: true,
      parking: true,
      gymNearby: false,
      pool: true,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: false,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: true,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["gym", "laundry", "kitchen", "busStop"],
      lifestyle: ["socialParty"],
    },
    description:
      "A popular Private Certified Housing option known for its social scene and amenities like an indoor pool. Often associated with Greek life.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=15",
    pros: [
      "Indoor pool",
      "Larger rooms with semi-private baths",
      "Social atmosphere",
    ],
    pros_zh: [],
    cons: ["Can be expensive", "Food quality varies"],
    cons_zh: [],
    price: 15000,
    priceRange: "$$$$",
    roomTypes: ["2B1B", "2B2B", "Suite"],
    floorPlans: [
      {
        type: "2B1B",
        price: 15000,
        sqft: 280,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BROMLEY-2B1B.png",
        description: "Double room with private bathroom",
        available: true,
      },
      {
        type: "2B2B",
        price: 15500,
        sqft: 320,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BROMLEY-2B2B.png",
        description: "Double room with private bathroom",
        available: true,
      },
      {
        type: "Suite",
        price: 15800,
        sqft: 400,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/BROMLEY-Suite.png",
        description: "Suite with shared living area",
        available: true,
      },
    ],
    lat: 40.107121375140615,
    lng: -88.23483418653669,
  },
  {
    id: "illini-tower",
    name: "Illini Tower",
    name_zh: "",
    location: "Campustown",

    housingType: "PCH",
    ac: true,
    dining: "inside",
    bathroomType: "private",
    tags: [
      "PCH",
      "Apartment Style",
      "Near Main Quad",
      "Near Green Street",
      "Convenient",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Parking",
      "Gym Nearby",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: true,
      parking: true,
      gymNearby: true,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: true,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["gym", "laundry", "convenienceStore", "busStop"],
      lifestyle: ["socialParty"],
    },
    description:
      "Located just blocks from the Main Quad and Green Street. Offers apartment-style living with full kitchens in some units.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=16",
    pros: ["Kitchens in units", "Close to everything", "Study lounges"],
    pros_zh: [],
    cons: ["Older building", "Elevator wait times"],
    cons_zh: [],
    price: 13500,
    priceRange: "$$$",
    roomTypes: ["Studio", "1B1B", "2B1B", "4B2B"],
    floorPlans: [
      {
        type: "Studio",
        price: 14200,
        sqft: 200,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ILLINITOWER-Studio.png",
        description: "Studio with full kitchen",
        available: true,
      },
      {
        type: "1B1B",
        price: 13800,
        sqft: 180,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ILLINITOWER-1B1B.png",
        description: "Single bedroom with shared bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 13500,
        sqft: 320,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ILLINITOWER-2B1B.png",
        description: "Two-bedroom with shared bathroom",
        available: true,
      },
      {
        type: "4B2B",
        price: 12800,
        sqft: 580,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ILLINITOWER-4B2B.png",
        description: "Four-bedroom suite with 2 baths",
        available: true,
      },
    ],
    lat: 40.10651744288508,
    lng: -88.2322944721566,
  },
  {
    id: "newman",
    name: "Newman Hall",
    name_zh: "",
    location: "Campustown",

    housingType: "PCH",
    ac: true,
    dining: "inside",
    bathroomType: "private",
    tags: [
      "PCH",
      "Catholic",
      "Community",
      "Near Main Quad",
      "Near Green Street",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Quiet Floors",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: true,
      parking: false,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: true,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["gym", "laundry", "studyLounge"],
      lifestyle: ["quiet"],
    },
    description:
      "Associated with St. John's Catholic Newman Center. Known for its strong community, central location, and good food.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=17",
    pros: ["Great location", "Tight-knit community", "Quiet study hours"],
    pros_zh: [],
    cons: ["Religious affiliation (may not be for everyone)", "Strict rules"],
    cons_zh: [],
    price: 12500,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "Studio", "2B2B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 12800,
        sqft: 125,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NEWMAN-1B1B.png",
        description: "Single room with shared bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 12500,
        sqft: 190,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NEWMAN-2B1B.png",
        description: "Double room with shared bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 13500,
        sqft: 160,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NEWMAN-Studio.png",
        description: "Private studio with kitchenette",
        available: true,
      },
      {
        type: "2B2B",
        price: 13800,
        sqft: 240,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/NEWMAN-2B2B.png",
        description: "Double room with private bathroom",
        available: true,
      },
    ],
    lat: 40.10573372686307,
    lng: -88.23002764961086,
  },
  {
    id: "hendrick",
    name: "Hendrick House",
    name_zh: "",
    location: "South Campus",

    housingType: "PCH",
    ac: true,
    dining: "nearby",
    bathroomType: "private",
    tags: [
      "PCH",
      "Foodie",
      "Near Main Quad",
      "Near Engineering",
      "Elevator",
      "Laundry",
      "Kitchen",
      "Gym Nearby",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: false,
      kitchen: true,
      parking: false,
      gymNearby: true,
      pool: false,
      genderInclusive: true,
      quietFloors: false,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: true,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["laundry", "kitchen", "studyLounge"],
      lifestyle: ["quiet"],
    },
    description:
      "Famous for its high-quality dining. Located near the engineering quad, making it a top choice for engineering students.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=18",
    pros: ["Best food on campus", "Close to engineering", "Comfortable rooms"],
    pros_zh: [],
    cons: ["Quieter social scene", "More expensive"],
    cons_zh: [],
    price: 14800,
    priceRange: "$$$$",
    roomTypes: ["1B1B", "2B1B", "Studio"],
    floorPlans: [
      {
        type: "1B1B",
        price: 15000,
        sqft: 140,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HENDRICK-1B1B.png",
        description: "Single room with private bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 14800,
        sqft: 250,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HENDRICK-2B1B.png",
        description: "Double room with private bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 15500,
        sqft: 180,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/HENDRICK-Studio.png",
        description: "Private studio with kitchenette",
        available: true,
      },
    ],
    lat: 40.11089292014344,
    lng: -88.21985099184408,
  },
  // Presby Hall - Ikenberry North area
  {
    id: "presby",
    name: "Presby Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "nearby",
    bathroomType: "private",
    tags: [
      "Social",
      "Quiet",
      "Modern",
      "Near Main Quad",
      "Near Ikenberry Dining",
      "Elevator",
      "Laundry",
      "Study Rooms",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: false,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: false,
      nearGreenStreet: false,
      nearIkenberryDining: true,
    },
    categorizedTags: {
      livingConditions: [],
      facilities: ["laundry", "kitchen", "studyLounge"],
      lifestyle: ["quiet"],
    },
    description:
      "A modern residence hall in Ikenberry North, offering a quiet study environment with air-conditioned rooms. Close to dining and academic buildings.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=20",
    pros: [
      "Quiet study environment",
      "Air conditioning",
      "Close to Ike dining",
      "Modern facilities",
    ],
    pros_zh: [],
    cons: [
      "Far from engineering quad",
      "Shared community bathrooms",
      "Longer walk to classes",
    ],
    cons_zh: [],
    price: 11500,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B"],
    floorPlans: [
      {
        type: "1B1B",
        price: 11800,
        sqft: 130,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/PRESBY-1B1B.png",
        description: "Single room with shared bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11200,
        sqft: 200,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/PRESBY-2B1B.png",
        description: "Double room with shared bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 10800,
        sqft: 280,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/PRESBY-3B1B.png",
        description: "Triple room with shared bathroom",
        available: true,
      },
    ],
    lat: 40.108249643315276,
    lng: -88.23263697408665,
  },
  // Armory Hall - Ikenberry area
  {
    id: "armory",
    name: "Armory Hall",
    name_zh: "",
    location: "Ikenberry",

    housingType: "URH",
    ac: true,
    dining: "nearby",
    bathroomType: "private",
    tags: [
      "Modern",
      "Renovated",
      "Quiet",
      "Near Main Quad",
      "Near ARC/CRCE",
      "Elevator",
      "Laundry",
      "Gym Nearby",
    ],
    structuredTags: {
      elevator: true,
      laundry: true,
      studyRooms: true,
      kitchen: false,
      parking: true,
      gymNearby: true,
      pool: false,
      genderInclusive: true,
      quietFloors: true,
      substanceFree: false,
      petFriendly: false,
      llc: [],
      // Proximity
      nearMainQuad: true,
      nearEngineering: false,
      nearBusiness: false,
      nearARC: true,
      nearGreenStreet: false,
      nearIkenberryDining: false,
    },
    categorizedTags: {
      livingConditions: ["newlyRenovated"],
      facilities: ["gym", "laundry", "busStop"],
      lifestyle: ["socialParty"],
    },
    description:
      "A recently renovated hall connecting to Presby. Features modern study spaces and proximity to campus recreation facilities. Popular for students who prefer a quieter environment.",
    description_zh: "",
    imageUrl: "https://picsum.photos/800/600?random=21",
    pros: [
      "Recently renovated (2012)",
      "Modern study spaces",
      "Quiet environment",
      "Close to ARC",
    ],
    pros_zh: [],
    cons: [
      "No dining hall in building",
      "Further from main quad",
      "Community bathrooms",
    ],
    cons_zh: [],
    price: 11800,
    priceRange: "$$$",
    roomTypes: ["1B1B", "2B1B", "3B1B", "Studio"],
    floorPlans: [
      {
        type: "1B1B",
        price: 12000,
        sqft: 135,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ARMORY-1B1B.png",
        description: "Single room with shared bathroom",
        available: true,
      },
      {
        type: "2B1B",
        price: 11600,
        sqft: 205,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ARMORY-2B1B.png",
        description: "Double room with shared bathroom",
        available: true,
      },
      {
        type: "3B1B",
        price: 11200,
        sqft: 285,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ARMORY-3B1B.png",
        description: "Triple room with shared bathroom",
        available: true,
      },
      {
        type: "Studio",
        price: 12500,
        sqft: 180,
        imageUrl:
          "https://housing.illinois.edu/Images/FloorPlans/ARMORY-Studio.png",
        description: "Private studio room",
        available: true,
      },
    ],
    lat: 40.1057022499472,
    lng: -88.2367063025306,
  },
]

const _DORM_NAME_ZH_BY_ID: Record<string, string> = {
  isr: "Illinois Street Residence (ISR)",
  nugent: "Nugent Hall",
  wassaja: "Wassaja Hall",
  bousefield: "Bousefield Hall",
  par: "Pennsylvania Avenue Residence (PAR)",
  far: "Florida Avenue Residence (FAR)",
  allen: "Allen Hall",
  "busey-evans": "Busey-Evans",
  snyder: "Snyder Hall",
  hopkins: "Hopkins Hall",
  weston: "Weston Hall",
  scott: "Scott Hall",
  taft: "Taft Hall",
  "van-doren": "Van Doren Hall",
  daniels: "Daniels Hall",
  sherman: "Sherman Hall",
  lar: "Lincoln Avenue Residence (LAR)",
  bromley: "Bromley Hall",
  "illini-tower": "Illini Tower",
  newman: "Newman Hall",
  hendrick: "Hendrick House",
  "eugene-field": "Eugene Field Hall",
  presby: "Presby Hall",
  armory: "Armory Hall",
}

const _LOCATION_ZH: Record<Dorm["location"], string> = {
  Ikenberry: "Ikenberry",
  "Main Quad": "Main Quad",
  "PAR/FAR": "PAR/FAR",
  Campustown: "Campustown",
  "South Campus": "South Campus",
}

const HOUSING_TYPE_ZH: Record<Dorm["housingType"], string> = {
  URH: "University Housing",
  PCH: "Private Certified Housing",
}

const buildDefaultProsZh = (dorm: Dorm): string[] => [
  `位于${dorm.location}，日常通勤较方便`,
  dorm.ac ? "配备空调，夏季居住更舒适" : "房间无空调，建议准备风扇",
  dorm.dining === "inside"
    ? "食堂可达，用餐便利"
    : "可选择周边餐饮，选择更灵活",
]

const buildDefaultConsZh = (dorm: Dorm): string[] => [
  `年费用约 $${dorm.price.toLocaleString()}，请结合预算评估`,
  dorm.housingType === "PCH"
    ? "私营宿舍管理规则与校内宿舍存在差异"
    : "高峰时段公共区域可能较拥挤",
  dorm.location === "Ikenberry" || dorm.location === "South Campus"
    ? "距离部分院系步行时间可能偏长"
    : "热门时段周边人流较多",
]

const enrichDormZhContent = (dorm: Dorm): Dorm => {
  // User requested English names for Dorms and Locations even in Chinese mode
  const nameZh = dorm.name // Use English name

  // Use English location name directly
  const locationZh = dorm.location

  const descriptionZh =
    dorm.description_zh?.trim() ||
    `${nameZh}位于${locationZh}，属于${HOUSING_TYPE_ZH[dorm.housingType]}。年住宿费用约 $${dorm.price.toLocaleString()}，${dorm.ac ? "配有空调" : "未配备空调"}，${dorm.dining === "inside" ? "就近可使用食堂。" : "需前往附近区域就餐。"}`

  const prosZh =
    dorm.pros_zh && dorm.pros_zh.length > 0
      ? dorm.pros_zh
      : buildDefaultProsZh(dorm)
  const consZh =
    dorm.cons_zh && dorm.cons_zh.length > 0
      ? dorm.cons_zh
      : buildDefaultConsZh(dorm)

  return {
    ...dorm,
    name_zh: nameZh,
    description_zh: descriptionZh,
    pros_zh: prosZh,
    cons_zh: consZh,
    location_zh: locationZh,
  }
}

export const UIUC_DORMS: Dorm[] = RAW_UIUC_DORMS.map(applyDormOfficialOverride)
  .map(finalizeDormRecord)
  .map(enrichDormZhContent)
  .map(normalizeDorm)

// Export dorm IDs for individual routes
export const DORM_IDS = UIUC_DORMS.map((dorm) => dorm.id)
