name: CI

on:
  pull_request:
    branches: ["**/*"]
  push:
    branches: ["**/*"]

jobs:
  check:
    name: Vite+ Check, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: git config --global url."https://x-access-token:${{ secrets.PRIVATE_REPO_PAT }}@github.com/".insteadOf "https://github.com/"
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true
          run-install: |
            args: ['--frozen-lockfile']
      - run: vp check
        continue-on-error: true
      - run: vp test
      - run: vp build
        working-directory: ./app
